// Generated by CoffeeScript 1.9.3
var build, color, fs, gulp, gutil, log, path;

fs = require('fs');

path = require('path');

gulp = require('gulp');

gutil = require('gulp-util');

color = gutil.colors;

log = gutil.log;

global.Cache = require('../../global/globalMap.json');

build = require('tms-widget-builder');


/*
 * ************* 构建任务函数 *************
 */

gulp.task('init', function() {
  return build.init();
});

gulp.task('less', function() {
  return build.less2js();
});

gulp.task('tpl', function() {
  return build.tpl2js();
});

gulp.task('js', ['less', 'tpl'], function() {
  return build.js2dist();
});

gulp.task('watch', function() {
  return build.watch();
});

gulp.task('server', function() {
  return build.server();
});

gulp.task('default', ['js', 'server'], function() {
  return gulp.start('watch');
});
